INSERT INTO UNIVERSITY VALUES ('ITCR')
INSERT INTO UNIVERSITY VALUES ('UCR')
INSERT INTO UNIVERSITY VALUES ('UNA')
INSERT INTO UNIVERSITY VALUES ('UNED')
INSERT INTO UNIVERSITY VALUES ('UTN')

INSERT INTO AIRPORT VALUES ('Annaba Les Salines', 'AnnLesSal', 'AAE', 'Algeria')
INSERT INTO AIRPORT VALUES ('Aalborg', 'Aal', 'AAL', 'Denmark')
INSERT INTO AIRPORT VALUES ('Mala Mala', 'Mal', 'AAM', 'South Africa')
INSERT INTO AIRPORT VALUES ('Al Ain', 'AAin', 'AAN', 'United Arab Emirates')
INSERT INTO AIRPORT VALUES ('Aeropuerto Internacional Juan Santamaría', 'AJS', 'SJO', 'Costa Rica')
INSERT INTO AIRPORT VALUES ('Anapa', 'Anap', 'AAQ', 'Russia')
INSERT INTO AIRPORT VALUES ('Altay', 'Alt', 'AAT', 'China')
INSERT INTO AIRPORT VALUES ('Araxa', 'Arax', 'AAX', 'Brazil')
INSERT INTO AIRPORT VALUES ('Al Ghaydah', 'AlG', 'AAY', 'Yemen')
INSERT INTO AIRPORT VALUES ('Albacete Los Llanos', 'AlbLl', 'ABC', 'Spain') 
INSERT INTO AIRPORT VALUES ('Abadan', 'Abad', 'ABD', 'Iran')
INSERT INTO AIRPORT VALUES ('Abilene Regional Airport', 'AbiRA', 'ABI', 'United States')
INSERT INTO AIRPORT VALUES ('Bamaga', 'Bam', 'ABM', 'Australia')
INSERT INTO AIRPORT VALUES ('Albuquerque International', 'AlbuIn', 'ABQ', 'United States')
INSERT INTO AIRPORT VALUES ('Aberdeen Municipal', 'AberdMun', 'ABR', 'United States')
INSERT INTO AIRPORT VALUES ('Abu Simbel', 'AbuSim', 'ABS', 'Egypt')
INSERT INTO AIRPORT VALUES ('Al Baha Al Aqiq', 'AlBahAq', 'ABT', 'Saudi Arabia')
INSERT INTO AIRPORT VALUES ('Abuja International', 'AbuIn', 'ABV', 'Nigeria')
INSERT INTO AIRPORT VALUES ('Aberdeen Dyce', 'AberDy', 'ABZ', 'United Kingdom')
INSERT INTO AIRPORT VALUES ('Acapulco Juan Alvarez International', 'AcaIn', 'ACA', 'Mexico')
INSERT INTO AIRPORT VALUES ('Accra Kotoka', 'AccKot', 'ACC', 'Ghana')
INSERT INTO AIRPORT VALUES ('Altenrhein', 'Altenr', 'ACH', 'Switzerland')
INSERT INTO AIRPORT VALUES ('Adiyaman', 'Adiy', 'ADF', 'Turkey')
INSERT INTO AIRPORT VALUES ('San Andres Island', 'SanAndIs', 'ADZ', 'Colombia')
INSERT INTO AIRPORT VALUES ('Arpt Jorge Newbery', 'BuAirJorNew', 'AEP', 'Argentina')
INSERT INTO AIRPORT VALUES ('Aalesund Vigra', 'AalVig', 'AES', 'Norway')
INSERT INTO AIRPORT VALUES ('Agadir Almassira', 'AgaAlm', 'AGA', 'Morocco')
INSERT INTO AIRPORT VALUES ('Agen La Garenne', 'AgGar', 'AGF', 'France')
INSERT INTO AIRPORT VALUES ('Helsingborg Angelholm', 'HelAng', 'AGH', 'Sweden')
INSERT INTO AIRPORT VALUES ('Agra Kheria', 'AgrKhe', 'AGR', 'India')
INSERT INTO AIRPORT VALUES ('Alghero Fertilia', 'AlgFer', 'AHO', 'Italy')
INSERT INTO AIRPORT VALUES ('Ahuas', 'Ahu', 'AHS', 'Honduras')
INSERT INTO AIRPORT VALUES ('Asahikawa', 'Asah', 'AKJ', 'Japan')
INSERT INTO AIRPORT VALUES ('Akulivik', 'Akul', 'AKV', 'Canada')
INSERT INTO AIRPORT VALUES ('Aktyubinsk', 'Akty', 'AKX', 'Kazakhstan')
INSERT INTO AIRPORT VALUES ('Ambon Pattimura', 'AmbPat', 'AMQ', 'Indonesia')
INSERT INTO AIRPORT VALUES ('Amsterdam Schiphol', 'AmsSch', 'AMS', 'Netherlands')
INSERT INTO AIRPORT VALUES ('Andahuaylas', 'Andah', 'ANS', 'Peru')
INSERT INTO AIRPORT VALUES ('Karpathos', 'Karp', 'AOK', 'Greece')
INSERT INTO AIRPORT VALUES ('Arthurs Town', 'ArthTown', 'ATC', 'Bahamas')
INSERT INTO AIRPORT VALUES ('Baracoa', 'Barac', 'BCA', 'Cuba')
INSERT INTO AIRPORT VALUES ('Bhadrapur', 'Bhad', 'BDP', 'Nepal')
INSERT INTO AIRPORT VALUES ('Belgrade Beograd', 'BelBeo', 'BEG', 'Serbia')
INSERT INTO AIRPORT VALUES ('Samana International', 'SamIn', 'AZS', 'Dominican Republic')
INSERT INTO AIRPORT VALUES ('Benghazi Benina Intl', 'BengBenInt', 'BEN', 'Libya')
INSERT INTO AIRPORT VALUES ('Berlin', 'Ber', 'BER', 'Germany')
INSERT INTO AIRPORT VALUES ('Aguadilla Borinquen', 'AguadBor', 'BQN', 'Puerto Rico')
INSERT INTO AIRPORT VALUES ('Hartsfield-Jackson', 'HartJack', 'ATL', 'United States')
INSERT INTO AIRPORT VALUES ('Aeropuerto Internacional de Los Ángeles', 'LA', 'LAX', 'United States')
INSERT INTO AIRPORT VALUES ('John F. Kennedy', 'JFK', 'JFK', 'United States')
INSERT INTO AIRPORT VALUES ('Aeropuerto Internacional de Miami', 'MIA', 'MIA', 'United States')
INSERT INTO AIRPORT VALUES ('Taba International', 'TabI', 'TCP', 'Egypt')
INSERT INTO AIRPORT VALUES ('Aeropuerto de Portela', 'Port', 'LIS', 'Portugal')
INSERT INTO AIRPORT VALUES ('Aeropuerto de Glamoč', 'Glam', 'LQGL', 'Bosnia Herzegovina')
INSERT INTO AIRPORT VALUES ('Aeropuerto de Dublin', 'DUB', 'DUB', 'Ireland')
INSERT INTO AIRPORT VALUES ('Aeropuerto de Eindhoven', 'Eind', 'EIN', 'Netherlands')

INSERT INTO AIRPLANES VALUES ('A380', 853, 1, 170)
INSERT INTO AIRPLANES VALUES ('B747', 467, 2, 93)
INSERT INTO AIRPLANES VALUES ('B777', 400, 3, 80)
INSERT INTO AIRPLANES VALUES ('A340', 375, 4, 75)
INSERT INTO AIRPLANES VALUES ('A330', 335, 5, 67)
INSERT INTO AIRPLANES VALUES ('A380', 853, 6, 170)
INSERT INTO AIRPLANES VALUES ('B747', 467, 7, 93)
INSERT INTO AIRPLANES VALUES ('B777', 400, 8, 80)
INSERT INTO AIRPLANES VALUES ('A340', 375, 9, 75)
INSERT INTO AIRPLANES VALUES ('A330', 335, 10, 67)
INSERT INTO AIRPLANES VALUES ('B737', 100, 11, 0)
INSERT INTO AIRPLANES VALUES ('A320', 220, 12, 44)
INSERT INTO AIRPLANES VALUES ('A319', 124, 13, 32)
INSERT INTO AIRPLANES VALUES ('A319', 156, 14, 0)
INSERT INTO AIRPLANES VALUES ('B737', 100, 15, 0)
INSERT INTO AIRPLANES VALUES ('A320', 220, 16, 44)

INSERT INTO ADMIN VALUES ('Joseph Rodríguez Vargas', '13243546', 'j.rv@gmail.com', 'Josephda8', 'imadmin', 'Supervisor')
INSERT INTO ADMIN VALUES ('Marck Castro Ramírez', '14253647', 'm.cr@gmail.com', 'Loladmin', 'chocolover', 'Supervisor')
INSERT INTO ADMIN VALUES ('Charles Rojas Montero', '10108080', 'c.rm@gmail.com', 'henkidama', 'm31_000h@', 'Supervisor')

INSERT INTO CUSTOMER VALUES ('José Daniel Montoya Salazar', '88888888', 'jd.m@gmail.com', 'Joseda8', 'green', 1)
INSERT INTO CUSTOMER VALUES ('José Núñez Valverde', '12345678', 'jc.n@gmail.com', 'Joselml', 'ice', 1)
INSERT INTO CUSTOMER VALUES ('Sebastián Mora', '87654321', 's.m@gmail.com', 'ElectroTECBoy', 'sunday', 1)
INSERT INTO CUSTOMER VALUES ('Marcelo Sánchez Solano', '66666666', 'm.ss@gmail.com', 'AzucarAmargo', 'lol', 1)

INSERT INTO CUSTOMER VALUES ('Kurt D', '12121515', 'kurt.d@gmail.com', 'Nevermind', 'smellslikeareference', 0)
INSERT INTO CUSTOMER VALUES ('Billie Joe A', '87909090', 'one_dollar_bill@gmail.com', 'Dookie', 'basketcase', 0)
INSERT INTO CUSTOMER VALUES ('Jane Doe', '00000000', 'jane.d@gmail.com', 'SomeGirl', 'somepassword', 0)
INSERT INTO CUSTOMER VALUES ('John Doe', '00000001', 'john.d@gmail.com', 'SomeMen', 'somepassword', 0)

INSERT INTO STUDENTS VALUES (1, 'Joseda8', 'UNED', 0)
INSERT INTO STUDENTS VALUES (2, 'Joselml', 'ITCR', 0)
INSERT INTO STUDENTS VALUES (3, 'ElectroTECBoy', 'UCR', 0)
INSERT INTO STUDENTS VALUES (4, 'AzucarAmargo', 'UNA', 0)
